version: '3.9'
services:
  image-splitter:
    build: .
    command:
      /app/node_modules/.bin/preact watch
    environment:
      - ENV_ID=dev
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/app/
    restart: always
    network_mode: bridge
    networks:
      - gratheon
networks:
  gratheon:
