version: '3.8'
services:
  web-app:
    build: .
    command:
      preact watch
    environment:
      - ENV_ID=prod
    ports:
      - 8080:8080
    volumes:
      - .:/app/
    restart: always
    network_mode: host
